# Site
repository: apmaciel/me
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andie Maciel
title: Programadora em formação
email: andie.pantoja.maciel@gmail.com
website: https://github.com/apmaciel/me

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: apmaciel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: andie-maciel-93999230a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Meu CV
  icon: fas fa-briefcase
  url: https://apmaciel.github.io/me/cv/curriculum-2024.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre Mim
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Olá, meu nome é Andie Maciel e sou estudante de análise e desenvolvimento de sistemas. Estou descobrindo a cada dia um universo fascinante de conhecimentos e aprendizados que a área da computação revela, e cada dia ávida a aprender mais. Por hora, meus interesses estão em entender como a web funciona, e sistemas computacionais de uso geral. 

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Educação # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FATEC SCS
        caption: 2024 - 2026
        sub_title: Análise e desenvolvimento de Sistemas
        quote: >
          As Faculdades de Tecnologia (Fatecs), mantidas pelo Centro Estadual de Educação Tecnológica "Paula Souza" (CEETEPS), têm por missão formar profissionais competentes e éticos, capazes de enfrentar desafios na busca do desenvolvimento tecnológico, social e econômico.
        description: | # this will include new lines to allow paragraphs
          Durante esta jornada de formação, estou me dedicando aos temas principais da minha graduação e buscando desenvolver habilidades e competências adjacentes e complementares, nas áreas de desenvolvimento multiplataforma, arquitetura e design de sistemas e todo o ciclo de vida que engloba a engenharia de software.

  - title: Um Pouco Mais Sobre Mim
    layout: text
    content: | # this will include new lines to allow paragraphs
      Além dos meus interesses na área de tecnologia da informação e desenvolvimento, tenho outros hobbies como:
      - Gastronomia
      - Música Pop
      - Natação
      - Passeios ao ar livre
      - Séries e filmes

# Footer
footer_show_references: true
references_title: Referências sob consulta

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
